SELECT
  COLUMN_NAME AS name
FROM INFORMATION_SCHEMA.COLUMNS
WHERE
  CONCAT('[', TABLE_SCHEMA, '].[', TABLE_NAME, ']') = '%TABLE_NAME%'
  AND COLUMNPROPERTY(object_id(TABLE_NAME), COLUMN_NAME, 'IsIdentity') = 1